debug_tag: 0

train_dictionary : ../file/noise_detect
model_file: model/model.pkl
normal_feature_dic: feature/normal_data
epoch: 10
batch_size: 512
test_batch_size: 32

ab_dictionary: ../file/noise_detect
max_fpr : 0.1

feature:
  n_mels: 128
  frames : 5
  n_fft: 10240
  hop_length: 5120
  power: 2.0


fit:
  compile:
    optimizer : adam
    loss : mean_squared_error
  epochs : 100
  batch_size : 128
  shuffle : True
  validation_split : 0.1
  verbose : 1

